### PR TITLE
Create Rock paper scissors

### PR DESCRIPTION
**Pull request by Diti2009**
please accept this, The date is almost nearing

### CODE REVIEW

**Review by CODING-Enthusiast9857 — APPROVED** [review]

**Comment by Diti2009** [comment]
Hi! Could you give me the label of Hacktoberfest-accepted

**Comment by Diti2009** [comment]
> Hi! Could you give me the label of Hacktoberfest-accepted

It would be great if you could hurry a bit since time is running ot.

**Comment by CODING-Enthusiast9857** [comment]
> > Hi! Could you give me the label of Hacktoberfest-accepted
> 
> It would be great if you could hurry a bit since time is running ot.

This repository was created for Hacktoberfest 2022. It is not for this year.

**Comment by Diti2009** [comment]
Ok!

**Pull request merged**
