### PR TITLE
Added solution to find middle element of a linked list in one iteration under C++, Algorithms

### PR DESCRIPTION
**Pull request by purbendu**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@purbendu 

**Thank you for contributing...!!**
- Please add your code in **Data Structures/C++** directory

Don't forget to give a ⭐ to the repository

**Comment by CODING-Enthusiast9857** [comment]
> Hello, you've asked to make some changes, can you kindly clarify what changes need to be made?

- Please add your code in Data Structures/C++ directory

**Comment by purbendu** [comment]
Made the above change, kindly review

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@purbendu 

- You have mistakenly created **.DS_Store binary files** 
- Please delete them & fix this issue

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@purbendu 

Great
Don't forget to give a ⭐ to the repository

**Pull request merged**
