### PR TITLE
Create clock.py

### PR DESCRIPTION
**Pull request by Prachi1000**
created clock using python

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@Prachi1000 

**Thank you for contributing...!!**
- Please make another directory as **Source code/Programs**
- add your code inside that directory

Don't forget to give a ⭐ to the repository

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@Prachi1000 

- You have not made requested changes yet 
- Do the following 
- Please make another directory as **Source code/Programs**
- add your code inside that directory

**Comment by Prachi1000** [comment]
ok mam

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@Prachi1000 

**Thank you for contributing...!!**
Don't forget to give a ⭐ to the repository

**Comment by Prachi1000** [comment]
can i add more???

**Comment by CODING-Enthusiast9857** [comment]
@Prachi1000 

You can contribute... But each time submit a new PR

**Pull request merged**
