### PR TITLE
Soduku_Solver

### PR DESCRIPTION
**Pull request by mohfaiz-123**
Backtracking

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@mohfaiz-123 

- Your code is not giving output please fix this issue
- then move your code inside **Programs/Java** folder

**Comment by mohfaiz-123** [comment]
please see the code works now..kindly merge..i do not see any java folder in your branch..

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@mohfaiz-123 


**Thank you** for contributing!
Don't forget to give a ⭐

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@mohfaiz-123 

- Your code is now working
- If folder not exist you need to create it 
- make java folder inside Programs folder and move your code

**Pull request closed without merging**
