### PR TITLE
Created Trie.java

### PR DESCRIPTION
**Pull request by roshanlam**
A basic Trie Data Structure in java

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@roshanlam 

- Your code has some errors, please solve it

**Comment by roshanlam** [comment]
Solved it

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@roshanlam 


- Main method is not present in your code
- please fix this issue

**Comment by roshanlam** [comment]
Main method is now present in the code

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@roshanlam 


**Thank you** for contributing...!!
Don't forget to give a ⭐

**Pull request merged**
