### PR TITLE
reverse linkedList

### PR DESCRIPTION
**Pull request by ankitkumar0622**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@ankitkumar0622 

- Delete all binary files

**Comment by ankitkumar0622** [comment]
Hey @CODING-Enthusiast9857 sorry for this but can you please be a little more specific about the binary files you're referring to .

**Comment by CODING-Enthusiast9857** [comment]
@ankitkumar0622 

Check C++ folder, you have mistakenly created some binary files. Delete them.

**Comment by ankitkumar0622** [comment]
Hi @CODING-Enthusiast9857 , can you please have a look at my request , I have made the changes .

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@ankitkumar0622 

- Delete all .exe files (binary)
- Files are still there

**Comment by ankitkumar0622** [comment]
Sorry for that , can you please check now.

**Comment by CODING-Enthusiast9857** [comment]
@ankitkumar0622 

- You have mistakenly deleted this file : https://github.com/CODING-Enthusiast9857/Hacktoberfest22-Contribute-DSA/pull/37/files#diff-827ed8364f6ba36645efdd25c0f117c420fff0b857ef310e19f2bfdcab472693
- Your original file is not present

**Comment by ankitkumar0622** [comment]
Can you please check now.

**Pull request merged**
