### PR TITLE
Added c++ code for Cyclic Detection in an undirected graph

### PR DESCRIPTION
**Pull request by kaneki-ken260**
I have added the code for Cyclic Detection in an undirected graph under the Algorithm Directory

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@kaneki-ken260 

**Thank you for contributing...!!**
- Please move your code in data structures directory
- remove .txt extension 

Don't forget to give a ⭐ to the repository

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@kaneki-ken260 

Please make the requested changes

**Comment by kaneki-ken260** [comment]
@CODING-Enthusiast9857 I have made the necessary changes

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@kaneki-ken260 

**Thank you** for contributing...!!
Don't forget to give a ⭐

**Pull request merged**
